title: CV | Presian Nedyalkov
description:  Presian Nedyalkov's Curriculum Vitae.
url: https://presiannedyalkov.github.io/cv/
baseurl: ''
theme_skin: blue
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - liquid_reading_time
    - jekyll-spaceship